<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="en" sourcelanguage="">
<context>
    <name>EditableGeoCsv</name>
    <message>
        <location filename="geocsv_plugin.py" line="61"/>
        <source>Add GeoCSV layer</source>
        <translation>Add GeoCSV layer...</translation>
    </message>
    <message>
        <location filename="geocsv_plugin.py" line="71"/>
        <source>Editable GeoCSV</source>
        <translation>Editable GeoCSV</translation>
    </message>
</context>
<context>
    <name>GeoCsvNewController</name>
    <message>
        <location filename="geocsv_controller.py" line="127"/>
        <source>invalid file path</source>
        <translation>Error: Invalid file path.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="188"/>
        <source>unknown csvt attribute: {}</source>
        <translation>Error: Unknown CSVT attribute: {}.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="190"/>
        <source>csv&lt;-&gt;csvt missmatch</source>
        <translation>Notice: csv&lt;-&gt;csvt missmatch.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="196"/>
        <source>csvt geometry type exception</source>
        <translation>Error: Wrong geometry information detected in CSVT file. Please set again.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="198"/>
        <source>no csvt file found</source>
        <translation>Notice: No CSVT file found.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="222"/>
        <source>error while loading csv</source>
        <translation>Error: An error occurred while loading the CSV file.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="212"/>
        <source>error in geometry selection</source>
        <translation>Error: No valid geometry information could be generated with selected fields. Please choose again.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="87"/>
        <source>The layer &quot;{}&quot; was created successfully.</source>
        <translation>The layer &quot;{}&quot; was created successfully.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="147"/>
        <source>Open GeoCSV File</source>
        <translation>Open GeoCSV file</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="324"/>
        <source>CSVT File Error</source>
        <translation>Notice: Error in CSVT file detected. Please set again.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="94"/>
        <source>The csvt file couldn&apos;t be updated on disk.</source>
        <translation>The CSVT file couldn&apos;t be updated on disk.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="324"/>
        <source>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</source>
        <translation>An error occurred while trying to update the CSVT file according to the new attribute types. Please update the CSVT file manually.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="154"/>
        <source>not utf8 encoded</source>
        <translation>Error: The selected csv file is not UTF-8 encoded.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="169"/>
        <source>error in converting</source>
        <translation>The conversion wasn&apos;t successful. Please convert to UTF-8 manually and try again.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="164"/>
        <source>backup created</source>
        <translation>Backup created</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="164"/>
        <source>Created backup on &quot;{}&quot;</source>
        <translation>Backup on &quot;{}&quot; created.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="166"/>
        <source>Converted</source>
        <translation>Converted</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="166"/>
        <source>Successfully converted to utf-8</source>
        <translation>CSV successfully converted to UTF-8.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="147"/>
        <source>Files (*.csv *.tsv *.*)</source>
        <translation>Text files (*.csv *.tsv *.txt);; All Files(*.*)</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="132"/>
        <source>invalid delimiter. expected &quot;{}&quot;</source>
        <translation>Erroneous delimiter detected. The delimiter should be a &quot;{}&quot;.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="335"/>
        <source>CSVT File created/updated.</source>
        <translation>CSVT File created/updated.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="335"/>
        <source>The CSVT file was successfully created/updated on disk.</source>
        <translation>The CSVT file has been created/updated.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="97"/>
        <source>PRJ File created.</source>
        <translation>PRJ file created.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="97"/>
        <source>The PRJ file was successfully created on disk.</source>
        <translation>The PRJ file has been created.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="192"/>
        <source>csvt file contains incorrect geo attributes</source>
        <translation>CSVT file contains incorrect geometry attributes. Please set manually.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="194"/>
        <source>csvt file contains too many geo attributes</source>
        <translation>CSVT file contains more than one geometry attribute. Please set manually.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="87"/>
        <source>GeoCSV Layer created</source>
        <translation>GeoCSV</translation>
    </message>
</context>
<context>
    <name>GeoCsvReconnectController</name>
    <message>
        <location filename="geocsv_controller.py" line="298"/>
        <source>Couldn&apos;t automatically restore csv layer &quot;{}&quot;</source>
        <translation>Couldn&apos;t automatically restore CSV layer &quot;{}&quot;</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="296"/>
        <source>Layer &quot;{}&quot; is successfully reconnected</source>
        <translation>Layer &quot;{}&quot; is successfully reconnected.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="296"/>
        <source>GeoCSV Layer reconnected</source>
        <translation>GeoCSV</translation>
    </message>
</context>
<context>
    <name>VectorLayerController</name>
    <message>
        <location filename="geocsv_controller.py" line="310"/>
        <source>CSV File updated</source>
        <translation>GeoCSV</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="310"/>
        <source>Changes to layer &quot;{}&quot; successfully stored in csv file.</source>
        <translation>Changes to layer &quot;{}&quot; successfully updated in CSV file.</translation>
    </message>
</context>
<context>
    <name>VectorLayerSaveConflictController</name>
    <message>
        <location filename="geocsv_controller.py" line="388"/>
        <source>Invalid path</source>
        <translation>Invalid path</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="388"/>
        <source>An error occured while trying to save file on new location. Please try again.</source>
        <translation>An error occurred while trying to save file to new location. Please try again.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="337"/>
        <source>CSVT file could not be updated</source>
        <translation>CSVT file could not be updated</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="337"/>
        <source>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</source>
        <translation>An error occurred while trying to update the CSVT file according to the new attribute types. Please update the CSVT file manually.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="331"/>
        <source>Error while updating attributes happend</source>
        <translation>Error while updating attributes happend</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="331"/>
        <source>An error occured while trying to update the attributes list. Nothing has been stored on disk.</source>
        <translation>An error occurred while trying to update the attributes list. Nothing has been stored on disk.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="342"/>
        <source>Geometry index violation</source>
        <translation>Geometry index violation</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="342"/>
        <source>You tried to delete an attribute which is providing geometry information. The change will not be saved to disk.</source>
        <translation>You deleted an attribute that was providing geometry information. This can lead to unpredictable behavour. Please exit edit mode without saving your changes.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="386"/>
        <source>CSV File updated</source>
        <translation>CSV file updated</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="386"/>
        <source>Changes to layer &quot;{}&quot; successfully stored in csv file.</source>
        <translation>Changes to layer &quot;{}&quot; successfully stored in CSV file.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="379"/>
        <source>Save File</source>
        <translation>Save File</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="379"/>
        <source>Files (*.csv *.tsv *.*)</source>
        <translation>Files (*.csv *.tsv *.*)</translation>
    </message>
</context>
<context>
    <name>geocsvDialogNew</name>
    <message>
        <location filename="geocsv_dialog_new.ui" line="14"/>
        <source>GeoCSV Editor</source>
        <translation>Add new GeoCSV layer</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="29"/>
        <source>Retry</source>
        <translation>Retry</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="286"/>
        <source>Cancel</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="43"/>
        <source>Save As</source>
        <translation>Save As...</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="59"/>
        <source>Error: The csv file could not be saved. File Lock?</source>
        <translation>The action can&apos;t be completed because the file couldn&apos;t be found or it is write protected (by another program?).</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="29"/>
        <source>Dateiname</source>
        <translation>Filename</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="52"/>
        <source>Durchsuchen...</source>
        <translation>Browse...</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="296"/>
        <source>Ok</source>
        <translation>OK</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="99"/>
        <source>WKT Field</source>
        <translation>WKT Field</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="113"/>
        <source>Point (Easting/Northing)</source>
        <translation>Easting/Northing (Point)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="132"/>
        <source>WKT</source>
        <translation>Well Known Text (WKT)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="177"/>
        <source>Easting Field</source>
        <translation>Easting Field (longitude or x)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="190"/>
        <source>Northing Field</source>
        <translation>Northing Field (latitude or y)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="277"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;a href=&quot;http://giswiki.hsr.ch/Editable_GeoCSV#Help&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#2b84d3;&quot;&gt;Help&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="224"/>
        <source>Convert</source>
        <translation>Convert</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="231"/>
        <source>Character set:</source>
        <translation>Character set:</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="247"/>
        <source>The csv File is not in UTF-8. Please convert it first
 (CAUTION: the original file will be overwritten):</source>
        <translation>The file is not UTF-8 encoded. Please choose the original encoding (Note: A backup file will be written and then it will be overwritten).</translation>
    </message>
</context>
</TS>
